import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';
import type { Narrative } from '../contracts/types';
import { permalinkShell } from '../scripts/build-permalinks';

// Root is this directory; `pnpm dev` / `pnpm build` pass it in.
//
// One switch runs through the whole file: `command === 'serve'`. Serving (plain dev and the
// Gate 3 app suite) reads the PUBLISHED content root over /@fs and turns the dev-only
// state-jump hook on; building reads the same artifacts from /content, where the deploy copies
// them, and folds the hook out. Both roots are `content/`, so dev and production differ in how
// the bytes are reached and in nothing else.
//
// Two content roots exist in this repo and only one of them is the product:
//
//   content/              published, generated by the pipeline. Dev, the build, the app e2e
//                         suite, the landing suite and the research suite all read this.
//   tests/fixtures/seed   the FROZEN Gate 2 grammar fixtures. Reached only through
//                         `__SEED_ROOT__`, which exists only in harness mode, so only
//                         harness.html and tests/e2e/grammar.spec.ts can see it.
//
// Harness mode (`vite app --mode harness`) is what adds that define. The production build takes
// app/index.html as its only input, so harness.html and everything it reaches, the seed root
// included, stay out of the shipped bundle.
const APP_ROOT = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(APP_ROOT, '..');
const CONTENT_ROOT = join(REPO_ROOT, 'content');
const SEED_ROOT = join(REPO_ROOT, 'tests', 'fixtures', 'seed');

// Blueprint 6.7, FROZEN. Field values are quoted from the blueprint; the share_target action
// stays relative (research Section 4 pitfall) and the icon set carries both purposes.
const MANIFEST = {
  name: 'Matterhorn',
  short_name: 'Matterhorn',
  id: '/app',
  start_url: '/app',
  scope: '/',
  display: 'standalone' as const,
  background_color: '#F2F1EC',
  theme_color: '#F2F1EC',
  icons: [
    { src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' as const },
    { src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' as const },
    { src: '/icons/maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' as const },
    { src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' as const },
  ],
  share_target: {
    action: '/share',
    method: 'GET' as const,
    params: { title: 'title', text: 'text', url: 'url' },
  },
};

/**
 * The production response headers, read out of vercel.json rather than restated here (AC-SEC-3).
 *
 * `vite preview` is the only local server that serves the built artifact, so it is the only place
 * a CSP can be proven against the page that ships. A CSP asserted from a copy of the string would
 * prove that two strings match; taking the deployed one means a header edited in vercel.json is
 * live in the preview suite on the next run, and an inline script or an `eval` the policy forbids
 * fails there instead of in production. The global `/(.*)` block is the one that carries it; the
 * per-path cache blocks are Vercel's routing and have no preview equivalent.
 */
function productionHeaders(): Record<string, string> {
  const config = JSON.parse(readFileSync(join(REPO_ROOT, 'vercel.json'), 'utf8')) as {
    headers: Array<{ source: string; headers: Array<{ key: string; value: string }> }>;
  };
  const global = config.headers.find((entry) => entry.source === '/(.*)');
  if (global === undefined) throw new Error('Matterhorn: vercel.json has no global /(.*) header block');
  return Object.fromEntries(global.headers.map((h) => [h.key, h.value]));
}

/**
 * `/n/{id}` in dev, answered with the same document the build emits (AC-APP-18).
 *
 * The build writes `app/dist/n/{id}/index.html` with `scripts/build-permalinks.ts`; serving has
 * no build to write into, so the shell is composed per request from the same function, over the
 * same published content root the app itself reads. Without this the dev server answers
 * `/n/mbg-stop` with the bare SPA fallback and the og tags exist only in a build nobody serves
 * during the suite. Emitting on boot instead would put generated files in the source tree;
 * composing per request keeps the tree clean and picks up a content edit without a restart.
 */
function permalinkShells(contentRoot: string, appRoot: string): Plugin {
  return {
    name: 'mth-permalink-shells',
    apply: 'serve',
    configureServer(server) {
      server.middlewares.use((request, response, next) => {
        const path = (request.url ?? '').split('?')[0] ?? '';
        const id = /^\/n\/([A-Za-z0-9-]+)\/?$/.exec(path)?.[1];
        const artifact = id === undefined ? '' : join(contentRoot, 'narratives', `${id}.json`);
        if (artifact === '' || !existsSync(artifact)) {
          next();
          return;
        }
        const narrative = JSON.parse(readFileSync(artifact, 'utf8')) as Narrative;
        server
          .transformIndexHtml(request.url ?? path, readFileSync(join(appRoot, 'index.html'), 'utf8'))
          .then((html) => {
            response.setHeader('content-type', 'text/html');
            response.end(permalinkShell(html, narrative));
          })
          .catch(next);
      });
    },
  };
}

export default defineConfig(({ command, mode }) => {
  const serving = command === 'serve';
  const harness = mode === 'harness';
  return {
    plugins: [
      react(),
      ...(serving ? [permalinkShells(CONTENT_ROOT, APP_ROOT)] : []),
      // Never in dev and never in the harness: the e2e suite must not have a worker between it
      // and the server. The plugin is simply not present when serving.
      ...(serving
        ? []
        : [
            VitePWA({
              strategies: 'injectManifest',
              srcDir: 'src',
              filename: 'sw.ts',
              injectRegister: null,
              devOptions: { enabled: false },
              manifest: MANIFEST,
              injectManifest: {
                globPatterns: ['**/*.{js,css,html,svg,png,webmanifest}'],
                // GSAP is the landing's Firefox-only fallback (landing/motion.ts): a browser with
                // native scroll-driven animations never imports it. Precaching it would hand that
                // browser 45 KB gzip of code it will never run, on install, which is exactly the
                // download the dynamic import exists to avoid. Firefox fetches it from the network
                // instead, and a Firefox reader who is offline gets the static final frames, which
                // is the same picture reduced motion shows. tests/e2e/landing-motion.spec.ts reads
                // the emitted manifest back, so this glob cannot silently stop matching.
                globIgnores: ['**/assets/{gsap,ScrollTrigger}-*.js'],
                // The worker stays unminified so `self.__WB_MANIFEST` survives verbatim for
                // workbox to inject into. It is a kilobyte of source, and a readable worker is
                // the right default for a product whose whole claim is an inspectable read path.
                minify: false,
              },
            }),
          ]),
    ],
    define: {
      __CONTENT_BASE__: JSON.stringify(serving ? `/@fs${CONTENT_ROOT}` : '/content'),
      __MTH_DEV__: JSON.stringify(serving),
      ...(harness ? { __SEED_ROOT__: JSON.stringify(`/@fs${SEED_ROOT}`) } : {}),
    },
    // host pinned to IPv4: vite's default `localhost` binds ::1 only on some machines, and the
    // screenshot config drives http://127.0.0.1. fs.allow opens the repo root so /@fs reaches
    // the content root, and only ever while serving.
    server: serving ? { host: '127.0.0.1', fs: { allow: [REPO_ROOT] } } : {},
    preview: { host: '127.0.0.1', headers: productionHeaders() },
    build: { rollupOptions: { input: join(APP_ROOT, 'index.html') } },
  };
});
