/**
 * Gate 1 acceptance suite for `pnpm validate:content` (blueprint 6.11).
 *
 * Written from the specification before the validator exists. Every check gets the shared
 * GOOD content root (exit 0) and at least one BAD root that must exit 1 while naming its
 * check slug and the offending file on the same output line, which is the CLI contract:
 * a per-check table on stdout plus FAIL lines on stderr naming file and check.
 *
 * Assertions match on the slug plus a distinctive fragment (the filename), never on whole
 * sentences, so wording and table layout stay the implementer's business.
 *
 * Fixtures are generated by tests/fixtures/validator/generate-tokens.mjs. Regenerate after
 * editing any fixture datum; the good roots carry real gate tokens stamped by that script.
 */
import { execFileSync } from 'node:child_process';
import { beforeAll, describe, expect, it } from 'vitest';

const F = 'tests/fixtures/validator';
const GOOD = `${F}/good`;
/** One `pnpm exec tsx` spawn per run; generous so a cold start is never a flake. */
const T = 60_000;

interface Run {
  code: number;
  stdout: string;
  stderr: string;
  /** stdout and stderr concatenated, which is where assertions look. */
  out: string;
}

function runValidator(dir: string): Run {
  try {
    const stdout = execFileSync(
      'pnpm',
      ['exec', 'tsx', 'scripts/validate-content.ts', '--dir', dir],
      { encoding: 'utf8', stdio: 'pipe' },
    );
    return { code: 0, stdout, stderr: '', out: stdout };
  } catch (e) {
    const err = e as { status: number | null; stdout: string; stderr: string };
    const stdout = String(err.stdout ?? '');
    const stderr = String(err.stderr ?? '');
    return { code: err.status ?? -1, stdout, stderr, out: `${stdout}\n${stderr}` };
  }
}

/**
 * The run failed, and some single line of output names both the failing check slug and the
 * offending file. One line, because a slug in the table and a filename ten rows away is not
 * a report of anything.
 */
function expectFailure(run: Run, slug: string, fileFragment: string): void {
  expect(run.code, `expected exit 1\n${run.out}`).toBe(1);
  const line = run.out.split('\n').find((l) => l.includes(slug) && l.includes(fileFragment));
  expect(
    line,
    `expected one output line naming check "${slug}" and file "${fileFragment}"\n${run.out}`,
  ).toBeTruthy();
}

/** The good root passed, and the per-check table shows this check ran. */
function expectGoodPass(run: Run, slug: string): void {
  expect(run.code, `the shared good fixture root must pass every check\n${run.out}`).toBe(0);
  expect(run.stdout).toContain(slug);
}

const SLUGS = [
  'schema',
  'orphans',
  'counts',
  'narration',
  'lexicon',
  'manifest',
  'seed',
  'url-index',
  'liveness',
  'feed',
] as const;

let good: Run;
let goodMethodologyExemption: Run;

beforeAll(() => {
  good = runValidator(GOOD);
  goodMethodologyExemption = runValidator(`${F}/lexicon/good-methodology-exemption`);
}, T * 2);

describe('CLI contract', () => {
  it('exits 0 on the complete good content root', () => {
    expect(good.code, good.out).toBe(0);
  });

  it('prints a per-check table naming all ten checks of 6.11', () => {
    for (const slug of SLUGS) expect(good.stdout, `check "${slug}" missing from the table`).toContain(slug);
  });

  it('fails when --dir points at a path that does not exist', () => {
    const run = runValidator(`${F}/does-not-exist`);
    expect(run.code, `an absent content root is a hard failure now\n${run.out}`).not.toBe(0);
    expect(run.out).toContain('does-not-exist');
  }, T);

  it('fails when the content root has no sources.json', () => {
    const run = runValidator(`${F}/cli/bad-no-sources`);
    expect(run.code, `a content root without a source registry is a failure\n${run.out}`).not.toBe(0);
    expect(run.out).toContain('sources.json');
  }, T);

  it('writes FAIL lines to stderr on a failing run', () => {
    const run = runValidator(`${F}/counts/bad-stored-counts`);
    expect(run.code).toBe(1);
    expect(run.stderr).toContain('FAIL');
  }, T);
});

// 6.11 check 1: every artifact validates against its JSON Schema.
describe('check: schema', () => {
  it('passes on the good root', () => expectGoodPass(good, 'schema'));

  it('fails on a narrative with a field of the wrong type', () => {
    // provenance.source_count is a number in 6.3; this fixture stores it as a string.
    expectFailure(runValidator(`${F}/schema/bad-field-type`), 'schema', 'mbg-poisoning.json');
  }, T);
});

// 6.11 check 2: zero orphan numbers, every Value.source_id and every citations[] id resolves.
describe('check: orphans', () => {
  it('passes on the good root', () => expectGoodPass(good, 'orphans'));

  it('fails on a Value whose source_id is not in sources.json', () => {
    expectFailure(
      runValidator(`${F}/orphans/bad-unresolved-source`),
      'orphans',
      'ppn-panic.json',
    );
  }, T);

  it('fails on a citations[] id that does not resolve', () => {
    expectFailure(
      runValidator(`${F}/orphans/bad-unresolved-citation`),
      'orphans',
      'case_library.json',
    );
  }, T);
});

// 6.11 check 3 with 6.5 derivation, plus the CF-1 additive optional `conflicts` field.
describe('check: counts', () => {
  it('passes on the good root', () => expectGoodPass(good, 'counts'));

  it('fails when stored counts disagree with recomputation from the panels', () => {
    expectFailure(runValidator(`${F}/counts/bad-stored-counts`), 'counts', 'mbg-poisoning.json');
  }, T);

  it('fails when a dueling narrative carries the wrong conflicts count', () => {
    // CF-1: conflicts is derived as the number of CountEntry items in the dueling panel.
    expectFailure(runValidator(`${F}/counts/bad-conflicts`), 'counts', 'mbg-poisoning.json');
  }, T);
});

// 6.11 check 4: 100 percent narration binding in both languages.
describe('check: narration', () => {
  it('passes on the good root', () => expectGoodPass(good, 'narration'));

  it('fails when a sentence els references an el_id that does not exist', () => {
    expectFailure(
      runValidator(`${F}/narration/bad-dangling-el`),
      'narration',
      'tariffs-pay.json',
    );
  }, T);

  it('fails when a panel has no sentence in one language', () => {
    expectFailure(
      runValidator(`${F}/narration/bad-uncovered-panel`),
      'narration',
      'mbg-poisoning.json',
    );
  }, T);
});

// 6.11 check 5 with the 6.9 lexicon, future-tense-harm patterns, and style rules.
describe('check: lexicon', () => {
  it('passes on the good root', () => expectGoodPass(good, 'lexicon'));

  it('fails on an EN verdict word in a narrative', () => {
    expectFailure(runValidator(`${F}/lexicon/bad-en-verdict`), 'lexicon', 'mbg-poisoning.json');
  }, T);

  it('fails on an ID verdict word in a narrative', () => {
    expectFailure(runValidator(`${F}/lexicon/bad-id-verdict`), 'lexicon', 'ppn-panic.json');
  }, T);

  it('fails on a future-tense-harm phrase in an echo outcome', () => {
    expectFailure(runValidator(`${F}/lexicon/bad-future-harm`), 'lexicon', 'ppn-panic.json');
  }, T);

  it('fails on an em dash in user-facing copy', () => {
    expectFailure(runValidator(`${F}/lexicon/bad-em-dash`), 'lexicon', 'tariffs-pay.json');
  }, T);

  it('fails on an emoji in user-facing copy', () => {
    expectFailure(runValidator(`${F}/lexicon/bad-emoji`), 'lexicon', 'tariffs-pay.json');
  }, T);

  it('exempts the methodology page describing what Matterhorn does not do', () => {
    // 6.9 scoped exemption. Same root as good/, with the verdict words in methodology.json
    // policy_65 only. Nothing else in the root uses them.
    expect(
      goodMethodologyExemption.code,
      `the 6.9 methodology exemption must be scoped, not absent\n${goodMethodologyExemption.out}`,
    ).toBe(0);
    expect(goodMethodologyExemption.stdout).toContain('lexicon');
  });
});

// 6.11 check 6: a complete GenerationManifest whose gate tokens verify against artifact bytes.
describe('check: manifest', () => {
  it('passes on the good root, whose tokens are real sha256 hashes over the canonical bytes', () =>
    expectGoodPass(good, 'manifest'));

  it('fails when artifact bytes were tampered with after the token was computed', () => {
    expectFailure(runValidator(`${F}/manifest/bad-tampered`), 'manifest', 'tariffs-pay.json');
  }, T);

  it('fails when a gate token is missing', () => {
    expectFailure(runValidator(`${F}/manifest/bad-missing-token`), 'manifest', 'ppn-panic.json');
  }, T);
});

// 6.11 check 7: zero fixtures, no artifact carries "seed": true.
describe('check: seed', () => {
  it('passes on the good root', () => expectGoodPass(good, 'seed'));

  it('fails on an artifact carrying "seed": true', () => {
    expectFailure(runValidator(`${F}/seed/bad-seed-flag`), 'seed', 'mbg-poisoning.json');
  }, T);
});

// 6.11 check 8: url_index referential integrity and exactly one fresh_demo entry.
describe('check: url-index', () => {
  it('passes on the good root', () => expectGoodPass(good, 'url-index'));

  it('fails on a pattern referencing a narrative that does not exist', () => {
    expectFailure(
      runValidator(`${F}/url-index/bad-dangling-narrative`),
      'url-index',
      'url_index.json',
    );
  }, T);

  it('fails when there are zero fresh_demo entries', () => {
    expectFailure(
      runValidator(`${F}/url-index/bad-zero-fresh-demo`),
      'url-index',
      'url_index.json',
    );
  }, T);

  it('fails when there are two fresh_demo entries', () => {
    expectFailure(
      runValidator(`${F}/url-index/bad-two-fresh-demo`),
      'url-index',
      'url_index.json',
    );
  }, T);
});

// 6.11 check 9 under the plan's liveness policy: recorded fields only, the validator never fetches.
describe('check: liveness', () => {
  it('passes on the good root, which records a dead_replaced entry and a corroborated 403', () =>
    expectGoodPass(good, 'liveness'));

  it('fails on a live entry whose notes record a status of 400 or worse with no corroboration', () => {
    expectFailure(
      runValidator(`${F}/liveness/bad-live-error-no-corroboration`),
      'liveness',
      'sources.json',
    );
  }, T);
});

// 6.11 check 10: feed integrity.
describe('check: feed', () => {
  it('passes on the good root', () => expectGoodPass(good, 'feed'));

  it('fails on an item referencing a narrative that does not exist', () => {
    expectFailure(runValidator(`${F}/feed/bad-dangling-item`), 'feed', 'feed.json');
  }, T);

  it('fails when one pack carries two heroes', () => {
    expectFailure(runValidator(`${F}/feed/bad-two-heroes`), 'feed', 'feed.json');
  }, T);

  it('fails when ppn-panic is not flagged via_dissect', () => {
    expectFailure(runValidator(`${F}/feed/bad-ppn-no-dissect`), 'feed', 'feed.json');
  }, T);
});
